version: '2'

services:
    nginx:
        build:
            context: ./Nginx
        ports:
            - 80:80
    fastapi:
        build:
            context: ./FastAPI
        volumes:
            - ./FastAPI/src:/var/www/app
    mongo:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./MongoDB/init:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
