version: '2'

services:
    nginx:
        build:
            context: ./Nginx
        ports:
            - 80:80
    fastapi:
        build:
            context: ./FastAPI
        volumes:
            - ./FastAPI/src:/var/www/app
        tty: true
        stdin_open: true
        environment:
            MONGO_USER: ${MONGO_USER}
            MONGO_PASSWORD: ${MONGO_PASSWORD}
    mongo:
        image: mongo
        ports:
            - 27017:27017
        restart: always
        volumes:
            - ./MongoDB/init:/docker-entrypoint-initdb.d
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/
